/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.lab6_fake;

import javax.swing.JOptionPane;

/**
 *
 * @author copbu
 */
public class NewStudentDialog extends javax.swing.JDialog {
 StudentManager studentManager = new StudentManager();
    /**
     * Creates new form NewStudentDialog
     */
    public NewStudentDialog() {
        
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        AddBt = new javax.swing.JButton();
        ClearBt = new javax.swing.JButton();
        lblStudentID = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        lblStudentName = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        lblStudentSchoolStage = new javax.swing.JLabel();
        maleRdBt = new javax.swing.JRadioButton();
        femaleRdBt = new javax.swing.JRadioButton();
        lblStudentGender = new javax.swing.JLabel();
        schoolStage = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        AddBt.setText("Add");
        AddBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtActionPerformed(evt);
            }
        });

        ClearBt.setText("Clear");
        ClearBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtActionPerformed(evt);
            }
        });

        lblStudentID.setText("Student's Id");

        Id.setText("enter Id");

        lblStudentName.setText("Student's Name:");

        name.setText("enter name");

        lblStudentSchoolStage.setText("School Stage:");

        buttonGroup1.add(maleRdBt);
        maleRdBt.setText("male");

        buttonGroup1.add(femaleRdBt);
        femaleRdBt.setText("female");

        lblStudentGender.setText("Student's Gender:");

        schoolStage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primary", "Secondary", "High School" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(ClearBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(AddBt)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schoolStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentGender, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(maleRdBt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(femaleRdBt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblStudentSchoolStage, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                        .addComponent(Id)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblStudentID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStudentName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStudentGender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleRdBt)
                    .addComponent(femaleRdBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStudentSchoolStage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(schoolStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBt)
                    .addComponent(ClearBt))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==ClearBt){
           name.setText("");
            Id.setText("");
            schoolStage.setSelectedIndex(0);
            buttonGroup1.clearSelection();
            
        }
    }//GEN-LAST:event_ClearBtActionPerformed

    private void AddBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==AddBt){
            name.getText();
            Id.getText();
            String gender="";
            String schoolStages="";
            if(maleRdBt.isSelected()){
                gender = "male";} 
            else if(femaleRdBt.isSelected()){
                gender = "female";}
            if(schoolStage.getSelectedIndex() != -1){
                schoolStages = (String) schoolStage.getItemAt(schoolStage.getSelectedIndex());}
        }
        Student student = new Student();
        if(studentManager.AddStudent(student)){
            JOptionPane.showMessageDialog(this, "Add Successfully");
            studentManager.getStudents().add(student);
        }else {
        JOptionPane.showMessageDialog(this, "Failed");}
    }//GEN-LAST:event_AddBtActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBt;
    private javax.swing.JButton ClearBt;
    private javax.swing.JTextField Id;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton femaleRdBt;
    private javax.swing.JLabel lblStudentGender;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblStudentSchoolStage;
    private javax.swing.JRadioButton maleRdBt;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> schoolStage;
    // End of variables declaration//GEN-END:variables
}
