/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;

import javax.swing.JFrame;

/**
 *
 * @author copbu
 */
public class FirstFrame extends javax.swing.JFrame {

    private login login = new login();
    private Frame frame = new Frame();
    
    /**
     * Creates new form FirstFrame
     */
    public FirstFrame() {
        initComponents();
         this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         this.setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startBt = new javax.swing.JButton();
        bigLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cyber Net Manager");
        setBackground(new java.awt.Color(0, 0, 0));

        startBt.setFont(new java.awt.Font("ROG Fonts", 0, 18)); // NOI18N
        startBt.setForeground(new java.awt.Color(0, 204, 51));
        startBt.setText("Start");
        startBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startBtMouseClicked(evt);
            }
        });
        startBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtActionPerformed(evt);
            }
        });

        bigLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\copbu\\Downloads\\Screenshot 2024-06-18 233240 (1).png")); // NOI18N
        bigLogo.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bigLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(startBt)
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bigLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startBt)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startBtMouseClicked
    
    }//GEN-LAST:event_startBtMouseClicked

    private void startBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==startBt){
            frame.setVisible(true);
        }
    }//GEN-LAST:event_startBtActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bigLogo;
    private javax.swing.JButton startBt;
    // End of variables declaration//GEN-END:variables
}
