package test;

public class login extends javax.swing.JPanel {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocation(500, 700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signUp = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        lbWelcome = new javax.swing.JLabel();
        Slogan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        userName = new javax.swing.JTextField();
        passWord = new javax.swing.JPasswordField();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lbLoginPage = new javax.swing.JLabel();
        logInBt = new javax.swing.JButton();
        cancelBt = new javax.swing.JButton();
        RegisterBt = new javax.swing.JButton();
        lblCreateAccount = new javax.swing.JLabel();

        signUp.setText("signUp");
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });

        setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\copbu\\Downloads\\Screenshot 2024-06-18 233240 (1).png")); // NOI18N

        lbWelcome.setFont(new java.awt.Font("Playbill", 0, 36)); // NOI18N
        lbWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWelcome.setText("Welcome!");

        Slogan.setFont(new java.awt.Font("Segoe Print", 2, 14)); // NOI18N
        Slogan.setText("Just Relax!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(lbWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Slogan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(lbWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Slogan)
                .addGap(56, 56, 56))
        );

        add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userName.setText("enter username....");
        jPanel2.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 252, -1));

        passWord.setText("jPasswordField1");
        jPanel2.add(passWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 250, -1));

        lblUserName.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(0, 139, 242));
        lblUserName.setText("Username: ");
        jPanel2.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 80, -1));

        lblPassword.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 136, 245));
        lblPassword.setText("Password: ");
        jPanel2.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 80, 30));

        lbLoginPage.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        lbLoginPage.setForeground(new java.awt.Color(51, 255, 51));
        lbLoginPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLoginPage.setText("Admin Login Page");
        jPanel2.add(lbLoginPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 220, 40));

        logInBt.setBackground(new java.awt.Color(0, 255, 51));
        logInBt.setText("Log in");
        jPanel2.add(logInBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        cancelBt.setBackground(new java.awt.Color(255, 0, 51));
        cancelBt.setForeground(new java.awt.Color(51, 51, 51));
        cancelBt.setText("Cancel");
        cancelBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtActionPerformed(evt);
            }
        });
        jPanel2.add(cancelBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        RegisterBt.setText("Register");
        RegisterBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtActionPerformed(evt);
            }
        });
        jPanel2.add(RegisterBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 100, 20));

        lblCreateAccount.setForeground(new java.awt.Color(204, 0, 0));
        lblCreateAccount.setText("Create new account:");
        jPanel2.add(lblCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 120, -1));

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed
        
    }//GEN-LAST:event_signUpActionPerformed

    private void RegisterBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == RegisterBt) {
            launchPage newWindow = new launchPage();
            newWindow.setVisible(true);
            
        }
    }//GEN-LAST:event_RegisterBtActionPerformed

    private void cancelBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == cancelBt) {
            
        }
    }//GEN-LAST:event_cancelBtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton RegisterBt;
    private javax.swing.JLabel Slogan;
    private javax.swing.JButton cancelBt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbLoginPage;
    private javax.swing.JLabel lbWelcome;
    private javax.swing.JLabel lblCreateAccount;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JButton logInBt;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JButton signUp;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables

    
}
